// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mobiphony.Models;

#nullable disable

namespace Mobiphony.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mobiphony.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("BatCapacity")
                        .HasColumnType("double");

                    b.Property<double>("BatChargingWattage")
                        .HasColumnType("double");

                    b.Property<double>("BluetoothVersion")
                        .HasColumnType("double");

                    b.Property<double>("Brightness")
                        .HasColumnType("double");

                    b.Property<string>("CPU")
                        .HasColumnType("longtext");

                    b.Property<string>("Chipset")
                        .HasColumnType("longtext");

                    b.Property<double>("Dsize")
                        .HasColumnType("double");

                    b.Property<double>("ExpStorageLimit")
                        .HasColumnType("double");

                    b.Property<bool>("FaceRec")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("FingerPrint")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("GPU")
                        .HasColumnType("longtext");

                    b.Property<int>("IPRating")
                        .HasColumnType("int");

                    b.Property<double>("InternalStorage")
                        .HasColumnType("double");

                    b.Property<double>("Length")
                        .HasColumnType("double");

                    b.Property<string>("MCFeatures")
                        .HasColumnType("longtext");

                    b.Property<double>("MCMP")
                        .HasColumnType("double");

                    b.Property<string>("MCVideo")
                        .HasColumnType("longtext");

                    b.Property<double>("Matrix")
                        .HasColumnType("double");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("NFC")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("OS")
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("RAM")
                        .HasColumnType("int");

                    b.Property<double>("RefreshRate")
                        .HasColumnType("double");

                    b.Property<double>("Resolution")
                        .HasColumnType("double");

                    b.Property<string>("SCFeatures")
                        .HasColumnType("longtext");

                    b.Property<double>("SCMP")
                        .HasColumnType("double");

                    b.Property<string>("SCVideo")
                        .HasColumnType("longtext");

                    b.Property<int>("SIM")
                        .HasColumnType("int");

                    b.Property<string>("ScrProtection")
                        .HasColumnType("longtext");

                    b.Property<double>("Thickness")
                        .HasColumnType("double");

                    b.Property<string>("USBType")
                        .HasColumnType("longtext");

                    b.Property<double>("USBVersion")
                        .HasColumnType("double");

                    b.Property<double>("WiFiSpeed")
                        .HasColumnType("double");

                    b.Property<double>("Width")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Phones");
                });
#pragma warning restore 612, 618
        }
    }
}
